version: '3.8'

services:
  frontend:
    image: clinical-trials/frontend
    build: ./clinical-trials-researcher
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8080:80" # Adjust if React runs on a different port

  backend:
    image: clinical-trials/backend
    build: ./
    volumes:
      - ./clinical-trials-data:/app/clinical-trials-data # Adjust or remove as needed
    env_file:
      - ./.env
    networks:
      - app-network
    ports:
      - "8000:8000" # FastAPI default port


networks:
  app-network:
    driver: bridge
