version: '3.8'

services:
  frontend:
    image: clinical-trials/frontend
    build: ./clinical-trials-researcher
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: clinical-trials/backend
    build: ./
    volumes:
      - ./clinical-trials-data:/app/clinical-trials-data # Adjust or remove as needed
    env_file:
      - ./.env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    volumes:
      - /home/austin/.cloudflared:/etc/cloudflared
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

